server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /fintech

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/fintech?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&allowLoadLocalInfile=true
    username: root
    password: 12345
    testWhileIdle: true
    validationQuery: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  docker:
  #    compose:
  #      enabled: true
  #      file: src/main/docker-compose/docker-compose.yml
  ##      readiness:
  #        tcp:
  #          connect-timeout: 200ms
  #          read-timeout: 200ms
  #        timeout: 2m
  #        wait: always
  #      lifecycle-management: start_and_stop

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    metrics:
      enabled: true
application:
  version: @project.version@